coverage:
  status:
    project:
      default:
        target: 80%
  range: 70..80
  round: down
  precision: 2

ignore:
  - 'node_modules/'
  - 'src/base/utils/document-component.tsx'
  - 'src/base/test-polyfill.js'
  - 'src/index.tsx.js'
  - 'src/setupTests.js'
  - 'src/rmwc/**/*'
  - 'src/**/*.story.*'
  - 'src/**/*.spec.*'
  - 'src/**/readme*'
  - 'src/doc-utils*'
